---
title: "figure_construction"
output: pdf_document
date: "2024-08-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **The feminization of labor conflict: A temporal and comparative analysis of global union density** Replication Manual 

## 1. Data

The data used in this research come from the construction of a longitudinal database (FDL) on labor relations based on the union of sources such as ICTWSS, OECD, ILO, and World Bank, which provide temporal information at the country level. To this is added the estimation and validation of the two main indicators for this study, which are female and male union density, which were constructed from household surveys, labor force surveys, and/or administrative data for the countries under study (see Appendix A). FDL is a longitudinal database that contains 3,360 observations and 340 labor, economic, and institutional variables based on information from 1960 to 2023 from 45 countries around the world.

The data used in the manuscript can be replicated following the steps below. All files were processed in R language (.R) using RStudio. 

### 1.1 Data folder

The data folder contains the following .csv and .xlsx archives: 

#### 1.1.1 employment_by_activities_and_status.csv

**Economic activities** are defined according to the Major divisions of the International standard International Classification (ISIC). Data are presented according to the latest revisions of the ISIC: Revision 3 (1990) and Revision 4 with the exception of the United States for which data is only available in Revision 2 until 2002 only.

In some cases, the data according to both revisions are updated while only the latest is revised in other cases. This explains why in some cases, the level of employment or the number of employees are different according to the two ISIC revisions. Unless otherwise specified in the country notes data are compiled from the Labour Force Surveys.

**Source:** “Employment by activities and status (ALFS)” dataset is a subset of the Annual Labour Force Statistics (ALFS) database which contains annual labour force statistics for the 36 OECD member countries plus Colombia, Costa Rica, Brazil and Russian Federation.

**Unit:** Data are presented in percentage of total employees

**Coverage:** 1955-2022

#### 1.1.2 employment_distribution_economic_activity_sex.csv

Employment distribution by economic activity (by sex) 

**Source:** ILO modeled statistics (2019)

#### 1.1.3 gender_wage_gap.csv

**Definition:** The gender wage gap is defined as the difference between median earnings of men and women relative to median earnings of men. Data refer to full-time employees on the one hand and to self-employed on the other.

**Source:** [OCDE](https://data.oecd.org/earnwage/gender-wage-gap.html)

**Unit:** Data are presented in percentage of total employees

**Coverage:** 1970-2023

#### 1.1.4 gender_share_part_time.csv !!!

#### 1.1.5 gdp_per_hour_worked.csv

**Definition:** GDP per hour worked is a measure of labour productivity. It measures how efficiently labour input is combined with other factors of production and used in the production process. Labour input is defined as total hours worked of all persons engaged in production. Labour productivity only partially reflects the productivity of labour in terms of the personal capacities of workers or the intensity of their effort. The ratio between the output measure and the labour input depends to a large degree on the presence and/or use of other inputs (e.g. capital, intermediate inputs, technical, organisational and efficiency change, economies of scale). This indicator is measured in USD (constant prices 2010 and PPPs) and indices.

**Source:** The default direct source for total hours worked is generally the OECD Annual National Accounts (ANA) Database. However, for a number of countries, long time series of hours worked are not available. For these countries, estimates from the OECD Employment Outlook are used. These are based on annual Labour Force Surveys (LFS) supplemented with information from a detailed OECD survey sent to member countries.

**Unit:** Average Annual rate of growth. 

**Coverage**: 1970-2023

#### 1.1.6 ICTWSS.xlsx !!!

**Coverage**: -2019

#### 1.1.7 incidence_full_time_part_time.csv

**Definition**: incidence and share consider only dependent workers. Limits of part time and full time emplyment are based on national definitions. 

**Source:** [Labor Force Survey](http://www.oecd.org/els/emp/LFS%20Definitions%20-%20Tables.pdf) for each country.

**Unit:** Data are presented in percentage of total employees

**Coverage**: !!!

#### 1.1.8 informal_employment.csv

**Definition:** Informal employment comprises persons who in their main jobs were unincorporated enterprises that produce at least partly for the market and are not registered. It excludes households that produce exclusively for own final use, subsistence agriculture, construction of own dwellings, etc. Some characteristics[^1] of informal imployment are: 
  - Lack of coverage by social security system;
  - Lack of entitlement to paid annual or sick leave;
  - Lack of written employment contract.
    
[^1]: For a more complete definition see [ILO](https://ilostat.ilo.org/resources/methods/description-informality/)

**Source:** ILOSTAT,International Labour Organization. 

The harmonized series on informality are derived by the Department of Statistics from processing national household survey microdata files using a consistent navigational path. The process involves identifying the production unit (formal sector, informal sector or household) and the nature of the job (formal job or informal job) of each employed person in their main job in order to derive the final indicators.

**Unit:** Data are presented in percentage of total employees

**Coverage**: 

#### 1.1.9 iso_code.xlsx

Contains the iso3c codes for all the countries considered in the database.

#### 1.1.10 labor_force_statistics.csv

**Definition**:  This dataset contains data on labour force participation rates, employment/population ratios and unemployment rates for both the total labour force and civilian labour force by sex. [LFS Definitions](http://www.oecd.org/els/emp/LFS%20Definitions%20-%20Tables.pdf)

**Source**: Labor Force Statistics dataset (OECD)

**Unit:** Data are presented in percentage of total employees

**Coverage:** 1966 - 2023

#### 1.1.11 real_minimun_wage.csv

**Definition**: Real hourly and annual minimum wages are statutory minimum wages converted into a common hourly and annual pay period for the 28 OECD countries and 4 non-member countries for which they are available. The resulting estimates are deflated by national Consumer Price Indices (CPI). The data are then converted into a common currency unit using US$ Purchasing Power Parities (PPPs) for private consumption expenditures.

Real hourly and annual minimum wages are calculated first by deflating the series using the consumer price index taking 2018 as the base year.  The series are then converted into a common currency unit (USD) using Purchasing Power Parities (PPPs) for private consumption expenditures in 2018.

**Unit:** US$ PurchasingPower Parities (PPPs)

**Source**: OECD

**Coverage:** 1970-2022

#### 1.1.12 time_spent_paid_unpaid_work.csv !!!!

### 1.2 Data construction

The archive *data-construction.R* contains the steps followed to create the database, which are:

1. Installing and opening the packages necessary to create the database. In this case: *tidyverse*, *data.table*, *openxlsx*, *magrittr* and *httr*.

2. Reading each dataset. 

3. Selecting the variables of interest in each dataset.

4. Selecting the year and country variables in each dataset.

5. Rename the variables in each dataset.

6. Tranforming the dataset from long format to wide format (if necessary).

7. Merging all the datasets.

8. Creating the *OCDE* column (assigns the code '1' to all the countries that are part of the organization)

9. Creating the *Continent* column (classifies each row depending on the observation's country)

10. Creating the ** column (blablabla) !!!

11. Saving the final database in .RData format.


# 2. Figures and tables

## 2.1 Introduction

All the figures from this chapter were constructed using the *introduction_figures.R* file, located in the processing folder. 

### *Figure 1.1*

1. **Packages used:** tidyverse environment, rwoldmap, sf
2. **Variables used:** country, iso3c, year,UD, UD_fem, UD_male
3. Create a world map, using the latest valid union density by gender (FUDI) data by country.
4. Blue shades indicate masculine union density, purple shades indicate femenine union density, white indicates neutral or NA values.

### *Figure 1.2*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** !!!!!!!!!!
3. Create a line chart for countries with feminine union density. The figure is a grid, with one figure for each country. The x-axis represents the years, and the y-axis represents the Union Density rates. The data is grouped and colored by gender, with "Femenine" (female) shown in magenta and "Masculine" (male) shown in a shade of blue.

### *Figure 1.3*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** !!!!!!!!!!
3. Create a line chart for countries with masculine union density. The figure is a grid, with one figure for each country. The x-axis represents the years, and the y-axis represents the Union Density rates. The data is grouped and colored by gender, with "Femenine" (female) shown in magenta and "Masculine" (male) shown in a shade of blue.

## 2.2 Chapter 1

### *Figure 2.1*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** OCDE, country, year, UD
3. Create a bar chart that displays Union Density (UD) for different countries that are part of the OECD. The x-axis represents the countries, and the y-axis represents the Union Density rates. There is a dashed horizontal line which represents the mean Union Density. 


### *Figure 2.2*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** OCDE, country, year, UD
3. Create a line chart  that shows Union Density (UD) over the years for various countries, excluding those in Africa. The x-axis represents the years, while the y-axis represents the Union Density rates. Each line represents a different country, and they are colored differently to distinguish between them. The grid is divided into multiple panels, each representing a different continent.

### *Figure 2.3*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** country, year, region, income, ser_empl, ind_empl, agr_emp
3. Create a line chart that displays the percentage of employment in three sectors (Agriculture, Industry, and Services) over the years for various regions.X-Axis represents the years, Y-Axis represents the percentage of employment in each sector.Different colors are used to represent each sector (Agriculture, Industry, Services).

### *Figure 2.4*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** country, year, LF_RATE__T, LF_RATE_F,LF_RATE_M
3. Create a line chart that displays the average percentage of wage and salaried workers over the years for different labor force categories. X-Axis represents the years and Y-Axis represents the average percentage of wage and salaried workers. Different colors are used to represent each labor force category (Total, Women, Men).

### *Figure 2.5*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** year, country, Part-time__T, Part-time_F, Part-time_M
3. Create a line chart that displays the average percentage of part-time employment over the years for different labor force categories. X-Axis represents the years and Y-Axis represents the average percentage of part-time employment. Different colors are used to represent each labor force category (Total, Women, Men). 

### *Figure 2.6*

1. **Packages used:** tidyverse environment, ggplot2
2. **Variables used:** year, country, rmw, UD
3. Create a scatter plot that displays Union Density (UD) against US Purchasing Power Parities (PPPs) for various countries. X-Axis Represents US Purchasing Power Parities (PPPs) in USD. Y-Axis represents Union Density (UD).Each point represents a country, the size of the points is proportional to the Union Density values.

### *Table 2.1*

1. **Packages used:** tidyverse environment, kable, kableExtra
2. **Variables used:** year, country, growth_ud
3. Create a table that presents data on Union Density across different decades for various countries. The table includes the following columns:

* *Country:* The names of the countries.
* *60-70:* Union Density data for the 1960s to 1970s.
* *80-90:* Union Density data for the 1980s to 1990s.
* *2000-:* Union Density data from the 2000s onwards.




